### ISSUE TITLE
Cannot compile for 32-bit

### ISSUE THREAD

**Issue by superlinkx** [leekchan/accounting#2]
Error:
leekchan/accounting/formatnumber.go:90: constant -9223372036854775808 overflows int

Won't compile for 32-bit architectures (main target is ARMv7)

**Comment by leekchan** [comment]
Sorry for my late reply.

I've added 32-bit support to the latest commit(a35854c075934d6aa1a6c1ab3ea8a82ee0dc1a93). The latest source will run on 32-bit machine.

Thanks.
