### ISSUE TITLE
Negative numbers print incorrectly

### ISSUE THREAD

**Issue by fsareshwala** [leekchan/accounting#3]
Negative numbers should print like `-$3,575.95` but they currently print like `$-3,575.95`.

**Comment by leekchan** [comment]
Hi. Thank you for your feedback. 

I changed the default format for negative numbers. (8bfe98e4b6af9416654a010f2c0e5ef88f74fa9a)

Please try again with the latest commit.

**Comment by fsareshwala** [comment]
Thanks for the quick fix. I was going to take a stab at it and am glad that it's already fixed 👍.
