### ISSUE TITLE
Blocking Urgent Problem

### ISSUE THREAD

**Issue by cristian-sima** [leekchan/accounting#6]
Hi.

It seems the package `github.com/cockroachdb/apd` was update yesterday and I am getting this.

```
github.com/leekchan/accounting
../../leekchan/accounting/formatnumber.go:79: d.ToStandard undefined (type *apd.Decimal has no field or method ToStandard)
../../leekchan/accounting/formatnumber.go:139: d.ToStandard undefined (type *apd.Decimal has no field or method ToStandard)
```

@leekchan Can you fix the problem?

**Comment by leekchan** [comment]
As mentioned in the pull request (https://github.com/cockroachdb/apd/pull/60),  ToStandard has been removed. But the author of the pull request said that it can be replaced by the 'f' format. 

@tamalsaha Could you fix the pull request #5? If you don't have enough time, I'll try it. Thanks!

**Comment by tamalsaha** [comment]
I am going to look into .

**Comment by cristian-sima** [comment]
Thanks guys
